export const INDIAN_CITIES = [
    "Agra, Uttar Pradesh",
    "Ahmedabad, Gujarat",
    "Ajmer, Rajasthan",
    "Aligarh, Uttar Pradesh",
    "Allahabad, Uttar Pradesh",
    "Amravati, Maharashtra",
    "Amritsar, Punjab",
    "Asansol, West Bengal",
    "Aurangabad, Maharashtra",
    "Bangalore, Karnataka",
    "Bareilly, Uttar Pradesh",
    "Belgaum, Karnataka",
    "Bhavnagar, Gujarat",
    "Bhilai, Chhattisgarh",
    "Bhiwandi, Maharashtra",
    "Bhopal, Madhya Pradesh",
    "Bhubaneswar, Odisha",
    "Bikaner, Rajasthan",
    "Bokaro Steel City, Jharkhand",
    "Chandigarh, Chandigarh",
    "Chennai, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Cuttack, Odisha",
    "Dehradun, Uttarakhand",
    "Delhi, Delhi",
    "Dhanbad, Jharkhand",
    "Durgapur, West Bengal",
    "Erode, Tamil Nadu",
    "Faridabad, Haryana",
    "Firozabad, Uttar Pradesh",
    "Ghaziabad, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Gulbarga, Karnataka",
    "Guntur, Andhra Pradesh",
    "Gurgaon, Haryana",
    "Guwahati, Assam",
    "Gwalior, Madhya Pradesh",
    "Hubli-Dharwad, Karnataka",
    "Hyderabad, Telangana",
    "Indore, Madhya Pradesh",
    "Jabalpur, Madhya Pradesh",
    "Jaipur, Rajasthan",
    "Jalandhar, Punjab",
    "Jammu, Jammu and Kashmir",
    "Jamnagar, Gujarat",
    "Jamshedpur, Jharkhand",
    "Jhansi, Uttar Pradesh",
    "Jodhpur, Rajasthan",
    "Kakinada, Andhra Pradesh",
    "Kalyan-Dombivli, Maharashtra",
    "Kannur, Kerala",
    "Kanpur, Uttar Pradesh",
    "Kochi, Kerala",
    "Kolhapur, Maharashtra",
    "Kolkata, West Bengal",
    "Kollam, Kerala",
    "Kota, Rajasthan",
    "Kozhikode, Kerala",
    "Kurnool, Andhra Pradesh",
    "Lucknow, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Madurai, Tamil Nadu",
    "Malappuram, Kerala",
    "Mangalore, Karnataka",
    "Mathura, Uttar Pradesh",
    "Meerut, Uttar Pradesh",
    "Moradabad, Uttar Pradesh",
    "Mumbai, Maharashtra",
    "Mysore, Karnataka",
    "Nagpur, Maharashtra",
    "Nanded, Maharashtra",
    "Nashik, Maharashtra",
    "Navi Mumbai, Maharashtra",
    "Nellore, Andhra Pradesh",
    "Noida, Uttar Pradesh",
    "Patna, Bihar",
    "Pimpri-Chinchwad, Maharashtra",
    "Pune, Maharashtra",
    "Raipur, Chhattisgarh",
    "Rajahmundry, Andhra Pradesh",
    "Rajkot, Gujarat",
    "Ranchi, Jharkhand",
    "Rourkela, Odisha",
    "Saharanpur, Uttar Pradesh",
    "Salem, Tamil Nadu",
    "Sangli, Maharashtra",
    "Siliguri, West Bengal",
    "Solapur, Maharashtra",
    "Srinagar, Jammu and Kashmir",
    "Surat, Gujarat",
    "Thane, Maharashtra",
    "Thiruvananthapuram, Kerala",
    "Thrissur, Kerala",
    "Tiruchirappalli, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Tiruppur, Tamil Nadu",
    "Ujjain, Madhya Pradesh",
    "Vadodara, Gujarat",
    "Varanasi, Uttar Pradesh",
    "Vasai-Virar, Maharashtra",
    "Vellore, Tamil Nadu",
    "Vijayawada, Andhra Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Warangal, Telangana"
];
